// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBulCOe1qbUeLG4AzCIVW9dOKlH_9qZDjo',
    appId: '1:119657201740:web:deca1ca4e94100fa84f4e9',
    messagingSenderId: '119657201740',
    projectId: 'app-distributeur',
    authDomain: 'app-distributeur.firebaseapp.com',
    storageBucket: 'app-distributeur.firebasestorage.app',
    measurementId: 'G-2JDZ0SY1KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChv4tgH_16Fywerh2Owgd0zAYESTvoYz8',
    appId: '1:119657201740:android:f7b2e0838c8b734284f4e9',
    messagingSenderId: '119657201740',
    projectId: 'app-distributeur',
    storageBucket: 'app-distributeur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8uNQITnVvwHOCk1ndJTW3e7Pt3x5KLbE',
    appId: '1:119657201740:ios:f3e7cd459e40912e84f4e9',
    messagingSenderId: '119657201740',
    projectId: 'app-distributeur',
    storageBucket: 'app-distributeur.firebasestorage.app',
    iosClientId: '119657201740-ot3t9bam6auls7jo9g0q7vekavn4b1ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8uNQITnVvwHOCk1ndJTW3e7Pt3x5KLbE',
    appId: '1:119657201740:ios:f3e7cd459e40912e84f4e9',
    messagingSenderId: '119657201740',
    projectId: 'app-distributeur',
    storageBucket: 'app-distributeur.firebasestorage.app',
    iosClientId: '119657201740-ot3t9bam6auls7jo9g0q7vekavn4b1ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBulCOe1qbUeLG4AzCIVW9dOKlH_9qZDjo',
    appId: '1:119657201740:web:e57280ef3341288684f4e9',
    messagingSenderId: '119657201740',
    projectId: 'app-distributeur',
    authDomain: 'app-distributeur.firebaseapp.com',
    storageBucket: 'app-distributeur.firebasestorage.app',
    measurementId: 'G-6N14X13SQE',
  );
}
